config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("content.urls", namespace="content")),
    path("", include("users.urls", namespace="users")),
    path("", include("subscription.urls", namespace="subscribe")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from content.apps import ContentConfig
from content.views import (
    IndexView,
    ContentCreate,
    PaidContentList,
    ContentDetail,
    ContentUpdate,
    ContentDelete,
    CollectionCreate,
    CollectionDetail,
    CollectionUpdate,
    CollectionDelete,
    CollectionList, MyContentList, MyCollectionList,
)

app_name = ContentConfig.name

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("post/create/", ContentCreate.as_view(), name="content_create"),
    path("post/<pk>/", ContentDetail.as_view(), name="content_detail"),
    path("post/<pk>/update/", ContentUpdate.as_view(), name="content_update"),
    path("post/<pk>/delete/", ContentDelete.as_view(), name="content_delete"),
    path("paid/", PaidContentList.as_view(), name="paid_content"),
    path("my_posts/", MyContentList.as_view(), name="my_content"),
    path("cols/", CollectionList.as_view(), name="collection_list"),
    path("my_cols/", MyCollectionList.as_view(), name="my_collection_list"),
    path("col/create/", CollectionCreate.as_view(), name="collection_create"),
    path("col/<pk>/", CollectionDetail.as_view(), name="collection_detail"),
    path("col/<pk>/edit/", CollectionUpdate.as_view(), name="collection_update"),
    path("col/<pk>/delete/", CollectionDelete.as_view(), name="collection_delete"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import Login, Register, UserRetrieve, ProfileUser, logout_user

app_name = UsersConfig.name

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", logout_user, name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("profile/", ProfileUser.as_view(), name="profile"),
    path("profile/<pk>/", UserRetrieve.as_view(), name="user_retrieve"),
]

content/models.py
from django.db import models

from users.models import User

NULL = {"null": True, "blank": True}


class Collection(models.Model):
    user = models.ForeignKey(
        User, related_name="collection_user", on_delete=models.CASCADE
    )
    name = models.CharField()
    description = models.TextField(**NULL)
    preview = models.ImageField(upload_to="collection_previews/", **NULL)

    def __str__(self):
        return self.name


class Content(models.Model):
    user = models.ForeignKey(
        User, related_name="content_user", on_delete=models.CASCADE
    )
    name = models.CharField()
    description = models.TextField()
    preview = models.ImageField(upload_to="content_previews/", **NULL)
    post_time = models.DateTimeField(auto_now_add=True)
    is_free = models.BooleanField()
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, **NULL)

    CATEGORY_CHOICES = [
        ("Art", "Art"),
        ("Poems", "Poems"),
        ("Education", "Education"),
        ("Entertainment", "Entertainment"),
        ("Not_selected", "Not selected"),
    ]
    category = models.CharField(choices=CATEGORY_CHOICES, default="Not selected")

    def __str__(self):
        return self.name

content/forms.py
from django import forms
from .models import Content, Collection

CATEGORY_CHOICES = [
    ("Not_selected", "Not selected"),
    ("Art", "Art"),
    ("Poems", "Poems"),
    ("Education", "Education"),
    ("Entertainment", "Entertainment"),
]


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ContentForm(StyleMixin, forms.ModelForm):
    collection = forms.ModelChoiceField(
        queryset=Collection.objects.none(), required=False
    )

    class Meta:
        model = Content
        fields = ("name", "description", "preview", "is_free", "category", "collection")
        labels = {
            "name": "Name",
            "preview": "Preview",
            "description": "Description",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-input"}),
            "preview": forms.FileInput(attrs={"class": "form-input"}),
            "description": forms.Textarea(attrs={"class": "form-input"}),
            "is_free": forms.Select(choices=((True, "Yes"), (False, "No"))),
            "category": forms.Select(
                choices=CATEGORY_CHOICES,
            ),
            "collection": forms.Select(attrs={"class": "form-input"}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["collection"].queryset = Collection.objects.filter(user=user)


class CollectionForm(StyleMixin, forms.ModelForm):
    name = forms.CharField(
        label="Name", widget=forms.TextInput(attrs={"class": "form-input"})
    )
    description = forms.CharField(
        label="Description", widget=forms.Textarea(attrs={"class": "form-input"})
    )
    preview = forms.ImageField(
        label="Preview",
        widget=forms.FileInput(attrs={"class": "form-input"}),
        required=False,
    )

    class Meta:
        model = Collection
        fields = ("name", "description", "preview")
        labels = {
            "name": "Name",
            "preview": "Preview",
            "description": "Description",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-input"}),
            "preview": forms.FileInput(attrs={"class": "form-input"}),
            "description": forms.Textarea(attrs={"class": "form-input"}),
        }

content/views.py
import stripe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.html import linebreaks
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic import CreateView, UpdateView, DeleteView

from config import settings
from subscription.models import Payment
from .forms import ContentForm, CollectionForm
from .models import Content, Collection


class IncMenu(TemplateView):
    template_name = "content/inc_menu.html"


class IndexView(TemplateView):
    template_name = "content/index.html"
    extra_context = {"title": "Main page"}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["object_list"] = Content.objects.filter(is_free=True)
        return context_data


class ContentCreate(LoginRequiredMixin, CreateView):
    model = Content
    form_class = ContentForm
    success_url = reverse_lazy("content:index")
    extra_context = {"title": "Create post"}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.collection = form.cleaned_data["collection"]
        self.object.save()
        return super().form_valid(form)


class PaidContentList(ListView):
    model = Content
    template_name = "content/paid_content_list.html"
    fields = "__all__"
    extra_context = {"title": "Paid content"}

    def get_queryset(self):
        if self.request.user.is_subscribed:
            return Content.objects.all()
        else:
            return Content.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        """Формируем данные для отображения в шаблоне страницы платного контента"""

        context_data = super().get_context_data(**kwargs)

        return context_data


class MyContentList(ListView):
    model = Content
    template_name = "content/my_content_list.html"
    fields = "__all__"
    extra_context = {"title": "My content"}

    def get_queryset(self):
        return Content.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        """Формируем данные для отображения в шаблоне страницы платного контента"""

        context_data = super().get_context_data(**kwargs)

        return context_data


class ContentDetail(DetailView):
    model = Content
    template_name = "content/content_detail.html"
    extra_context = {"title": "Post detail"}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get("pk"))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        content_item = Content.objects.get(pk=self.kwargs.get("pk"))
        context_data["title"] = content_item.name
        return context_data


class ContentUpdate(LoginRequiredMixin, UpdateView):
    model = Content
    form_class = ContentForm
    template_name = "content/content_update.html"
    success_url = reverse_lazy("content:content_detail")
    extra_context = {"title": "Post edit"}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.collection = form.cleaned_data["collection"]
        self.object.save()
        return super().form_valid(form)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get("pk"))
        return queryset

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("You do not have permission to edit this content")
        return obj


class ContentDelete(DeleteView):
    model = Content
    template_name = "content/content_delete.html"
    success_url = reverse_lazy("content:index")
    extra_context = {"title": "Delete post"}

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("You do not have permission to delete this content")
        return obj


class CollectionList(ListView):
    model = Collection
    template_name = "content/collection_list.html"
    fields = "__all__"
    extra_context = {"title": "Collections"}

    def get_queryset(self):
        return Collection.objects.all()

    def get_context_data(self, **kwargs):
        """Формируем данные для отображения в шаблоне страницы платного контента"""

        context_data = super().get_context_data(**kwargs)

        return context_data


class MyCollectionList(ListView):
    model = Collection
    template_name = "content/my_collection_list.html"
    fields = "__all__"
    extra_context = {"title": "My ollections"}

    def get_queryset(self):
        return Collection.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):

        context_data = super().get_context_data(**kwargs)

        return context_data


class CollectionCreate(LoginRequiredMixin, CreateView):
    model = Collection
    form_class = CollectionForm
    success_url = reverse_lazy("content:index")
    extra_context = {"title": "New collection"}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class CollectionDelete(DeleteView):
    model = Collection
    success_url = reverse_lazy("content:index")
    template_name = "content/collection_delete.html"
    extra_context = {"title": "Delete collection"}

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("You do not have permission to delete this collection")
        return obj


class CollectionUpdate(LoginRequiredMixin, UpdateView):
    model = Collection
    form_class = CollectionForm
    success_url = reverse_lazy("content:collection_detail")
    extra_context = {"title": "Edit collection"}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get("pk"))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        content_item = Collection.objects.get(pk=self.kwargs.get("pk"))
        context_data["title"] = content_item.name
        return context_data

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("You do not have permission to edit this collection")
        return obj


class CollectionDetail(DetailView):
    model = Collection
    extra_context = {"title": "Collection detail"}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get("pk"))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        collection_item = Collection.objects.get(pk=self.kwargs.get("pk"))
        collection = self.object
        context_data["title"] = collection_item.name
        context_data["posts"] = Content.objects.filter(collection=collection)
        return context_data

content/templates/content/base.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
    <title>{{ title }}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <style>
        /* Общие стили */
        .dark-font {
          color: #333; /* Replace with your desired dark color code */
        }
        .d-flex {
          display: flex;
          justify-content: center; /* Horizontally center the items */
          align-items: center; /* Vertically center the items */
          flex-direction: column; /* Stack the items vertically */
        }
        .container {
            max-width: 960px;
            margin: 0 auto;
        }
        .row {
            display: flex;
            flex-wrap: wrap;
            margin: 0 -10px;
        }
        .feed-item {
            border: 1px solid #e1e1e1;
            border-radius: 5px;
            margin: 10px;
            padding: 10px;
        }
        .user-info {
            font-weight: bold;
            display: flex;
            align-items: center;
        }
        .username-box {
            margin-left: 10px;
        }
        .post-content {
            margin-top: 10px;
        }
        /* Стили для аватаров */
        .account-img {
            width: 28px;
            height: 28px;
            object-fit: cover;
        }
        .rounded-circle {
            border-radius: 50%;
        }
        /* Стили для изображений */
        .media {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
        }
        .img-thumbnail {
            border: 1px solid #e1e1e1;
            border-radius: 5px;
            padding: 5px;
        }
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary">
{% if not user.is_authenticated %}
    <script>
        window.location.replace("{% url 'users:register' %}");
    </script>
{% endif %}

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3">
    <h2 class="h2">Paid content posting platform</h2>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/profile/{{ user.pk }}/">{{request.user.name}}</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>
</div>

{% include 'content/include/inc_menu.html' %}

{% block content%}
{% endblock %}
<footer>
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Paid content posting platform</p>
	</div>
</td></tr>
</footer>

<script src="{% static 'js/bundle.min.js' %}"></script>
<script src='{% static "/js/color-modes.js" %}'></script>
</body>
</html>

content/templates/content/collection_delete.html
{% extends 'content/base.html' %}
{% block content %}
  <h2>Are you sure you want to delete this collection?</h2>
  <form method="post">
    {% csrf_token %}
    <p> {{ object }} </p>
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

content/templates/content/collection_form.html
{% extends 'content/base.html' %}

{% block content %}
<h2>Create collection</h2>
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

content/templates/content/content_form.html
{% extends 'content/base.html' %}

{% block content %}
<h2>Create post</h2>
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

content/templates/content/index.html
{% extends 'content/base.html' %}
{% block content %}
{% load myfilters %}
<body>
<div class="container">
    <div class="row">
        {% for object in object_list reversed %}
    </div>

    <div class="row">
        <div class="feed-item">
            <div class="media user-media" style="display: flex; align-items: center;">
                {% if object.user.photo %}
                <a href="/profile/{{ object.user.pk }}" class="media" style="display: flex;">
                    <img class="rounded-circle account-img" src="{{ object.user.photo.url }}" width="28" height="28">
                </a>
                {% endif %}
                <div class="user-info" style="display: flex; align-items: center;">
                    <a href="/profile/{{ object.user.pk }}" style="text-decoration: none; color: inherit;">
                        @{{ object.user }}
                    </a>
                    {% if object.collection %}
                    <p style="margin: 0 8px;">from</p>
                    <a href="/col/{{ object.collection.pk }}">{{ object.collection }}</a>
                    {% endif %}
                    {% if object.user == request.user %}
                    <div class="d-flex justify-content-end">
                        <div class="btn-group">
                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Actions
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item"
                                       href="{% url 'content:content_update' object.pk %}">Update</a></li>
                                <li><a class="dropdown-item"
                                       href="{% url 'content:content_delete' object.pk %}">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                </div>

            </div>
            {% if object.preview %}
            <div style="display: flex; justify-content: center;">
                <img src="{{ object.preview.url }}" alt="Preview" style="max-width: 82%;">
            </div>
            {% endif %}
            <div class="post-content">
                <p>{{ object.description|linebreaksbr|truncatewords:125 }}</p>
            </div>
            <div style="display: flex; justify-content: space-between;">
                <a class="d-inline-flex focus-ring focus-ring-dark py-1 px-2 text-decoration-none border rounded-2"
                   href="/post/{{ object.pk }}">Open the post</a>
                <p>{{ object.post_time|custom_timesince }} ago</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</body>


{% endblock %}

content/templates/content/my_content_list.html
{% extends 'content/base.html' %}
{% block content %}
{% load myfilters %}
<body>
<div class="container">
    <div class="row">
        {% for object in object_list reversed %}
    </div>

    <div class="row">
        <div class="feed-item">
            <div class="media user-media" style="display: flex; align-items: center;">
                {% if object.user.photo %}
                <a href="/profile/{{ object.user.pk }}" class="media" style="display: flex;">
                    <img class="rounded-circle account-img" src="{{ object.user.photo.url }}" width="28" height="28">
                </a>
                {% endif %}
                <div class="user-info" style="display: flex; align-items: center;">
                    <a href="{% url 'users:user_retrieve' object.user.pk %}" style="text-decoration: none; color: inherit;">@{{ object.user }}</a>
                    {% if object.collection %}
                    <p style="margin: 0 8px;">from</p>
                    <a href="/col/{{ object.collection.pk }}">{{ object.collection }}</a>
                    {% endif %}
                </div>
            </div>
            {% if object.preview %}
            <img src="{{ object.preview.url }}" alt="Preview" style="max-width: 75%; display: block;">
            {% endif %}
            <div class="post-content">
                <p>{{ object.description|linebreaksbr|truncatewords:125 }}</p>
            </div>
            <div style="display: flex; justify-content: space-between;">
                <a class="btn btn-lg btn-block btn-outline-primary" href="/post/{{ object.pk }}">Open the post</a>
                <p>{{ object.post_time|custom_timesince }} ago</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</body>


{% endblock %}