config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("content.urls", namespace="content")),
    path("", include("users.urls", namespace="users")),
    path("", include("subscription.urls", namespace="subscribe")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import Login, Register, UserRetrieve, ProfileUser, logout_user

app_name = UsersConfig.name

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", logout_user, name="logout"),
    path("register/", Register.as_view(), name="register"),
    path("profile/", ProfileUser.as_view(), name="profile"),
    path("profile/<pk>/", UserRetrieve.as_view(), name="user_retrieve"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    phone = models.CharField(max_length=35, unique=True)
    name = models.CharField(max_length=100, unique=True)
    photo = models.ImageField(upload_to="users/", null=True, blank=True)
    is_subscribed = models.BooleanField(default=False)

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.name}"

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
    PasswordChangeForm,
)

from django import forms
from content.forms import StyleMixin
from users.models import User


class LoginUserForm(StyleMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ["password"]


class RegisterUserForm(StyleMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["name", "phone", "password1", "password2"]
        labels = {
            "phone": "Phone Number",
            "name": "Name",
        }
        widgets = {
            "phone": forms.TextInput(attrs={"class": "form-control"}),
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("This phone already exists")
        return phone


class ProfileUserForm(StyleMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ["phone", "name", "photo"]
        labels = {
            "phone": "Phone",
            "name": "Name",
            "photo": "Photo",
        }
        widgets = {
            "phone": forms.TextInput(attrs={"class": "form-control"}),
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "photo": forms.FileInput(attrs={"class": "form-select-image"}),
        }

users/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from content.models import Content
from users.forms import ProfileUserForm, LoginUserForm, RegisterUserForm
from users.models import User


class Login(LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {"title": "Authorization"}

    def get_success_url(self):
        return reverse_lazy("users:profile")


def logout_user(request):
    logout(request)
    return redirect("users:login")


class Register(CreateView):
    form_class = RegisterUserForm
    template_name = "users/register.html"
    extra_context = {"title": "Registration"}
    success_url = reverse_lazy("content:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        user = authenticate(
            phone=form.cleaned_data["phone"], password=form.cleaned_data["password1"]
        )
        if user is not None:
            login(self.request, user)
        return response


class UserRetrieve(DetailView):
    model = User
    template_name = "users/user_retrieve.html"
    extra_context = {"title": "User's profile"}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(pk=self.kwargs.get("pk"))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context["title"] = user.name
        context["posts"] = Content.objects.filter(user=user)
        return context


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileUserForm
    template_name = "users/profile.html"
    extra_context = {
        "title": "Edit profile",
    }

    def get_success_url(self):
        return reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'content/base2.html' %}
{% block content %}
<main class="form-signin w-100 m-auto">
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Authorization</h1>
        <div class="form-error">{{ form.non_field_errors }}</div>
        <div class="form-floating">
            {{ form.username }}
            <label for="floatingInput">Phone</label>
        </div>
        <div class="form-floating">
            {{ form.password }}
            <label for="floatingPassword">Password</label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Log in</button>
        <p class="text-body-secondary">If you don't have an account <a href="{% url 'users:register' %}">register</a></p>
        <p class="mt-5 mb-3 text-body-secondary">&copy; 2023–2024</p>
    </form>
</main>


{% endblock %}

users/templates/users/profile.html
{% extends 'content/base.html' %}
{% load static %}
{% block content %}
{% load cropping %}
<div class="container">
    <div class="row">
        <div class="form-signin w-100 m-auto">
            <h1>Profile</h1>

            {% if user.photo %}
            <div class="media">
                <img class="rounded-circle account-img" src="{{ user.photo.url }}" width="100" height="100">
                <div class="media-body">
                    {% endif %}

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p class="form-control">
                            <label for="id_phone">Phone:</label>
                            {{ form.phone }}
                        </p>
                        <p class="form-control">
                            <label for="id_name">Name:</label>
                            {{ form.name }}
                        </p>
                        <p class="form-select-image">
                            <label for="id_photo">Photo:</label>
                            {{ form.photo }}
                        </p>
                        <button type="submit">Save</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'content/base2.html' %}
{% block content %}


<main class="form-signin w-100 m-auto">
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Registration</h1>
        <div class="form-error">{{ form.non_field_errors }}</div>
        <div class="form-floating">
            {{ form.name }}
            <label for="floatingInput">Name</label>
            <div class="form-error">{{ form.errors.name }}</div>
        </div>
        <div class="form-floating">
            {{ form.phone }}
            <label for="floatingInput">Phone Number</label>
            <div class="form-error">{{ form.errors.phone }}</div>
        </div>
        <div class="form-floating">
            {{ form.password1 }}
            <label for="floatingPassword">Password</label>
            <div class="form-error">{{ form.errors.password1 }}</div>
        </div>
        <div class="form-floating">
            {{ form.password2 }}
            <label for="floatingPassword">Confirm Password</label>
            <div class="form-error">{{ form.errors.password2 }}</div>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Register</button>
        <p class="text-body-secondary">If you already have an account <a href="{% url 'users:login' %}">log in</a></p>
        <p class="mt-5 mb-3 text-body-secondary">&copy; 2023–2024</p>
    </form>
</main>


{% endblock %}

users/templates/users/user_retrieve.html
{% extends 'content/base.html' %}
{% block content %}
{% load myfilters %}
<body>
<div style="text-align: center;">
    <div>
    <h1 style="display: inline-block;">{{ user.name }}'s </h1>
    <h2 style="display: inline-block;">profile</h2>

    {% if user == request.user %}
    <a class="btn btn-link display: inline-block;" href="/profile/" style="display: inline-block;">Edit my profile</a>
    {% endif %}
    </div>
</div>
<div class="row">
    <div class="feed-item">
        <div class="media">

            {% if posts %}

            <div class="container">
                    {% for object in posts reversed %}

                <div class="row">
                    <div class="feed-item">
                        {% if object.user.photo %}
                        <div class="media" style="display: inline-block;">
                            <img class="rounded-circle account-img" src="{{ object.user.photo.url }}" width="28"
                                 height="28">
                        </div>
                        {% endif %}
                        <div class="user-info" style="display: inline-block;">
                            <div class="username-box">
                                <a>@{{ object.user }}</a>
                            </div>
                        </div>
                        {% if object.preview %}
                        <img src="{{ object.preview.url }}" alt="Preview"
                             style="max-width: 75%; display: block;">
                        {% endif %}
                        <div class="post-content">
                            <p>{{ object.description|linebreaksbr|truncatewords:125 }}</p>
                        </div>
                        <div style="display: flex; justify-content: space-between;">
                            <a class="btn btn-lg btn-block btn-outline-primary" href="/post/{{ object.pk }}">Open
                                the post</a>
                            <p>{{ object.post_time|custom_timesince }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
</body>
{% endblock %}